import type { State, Product } from "./types";
import { today } from "./engine";
export const sid = (n: number) =>
  "00000000-0000-4000-8000-" + String(n).padStart(12, "0");
export function emptyState(): State {
  return {
    materials: [],
    parts: [],
    products: [],
    customers: [],
    suppliers: [],
    purchases: [],
    losses: [],
    transformations: [],
    orders: [],
    productions: [],
    movements: [],
    sales: [],
    expenses: [],
    audit: [],
    settings: {
      name: "Bicou Brincou",
      subtitle: "by Peck Fun",
      phone: "",
      email: "",
      address: "",
      logo: "",
      lossRate: 10,
      taxRate: 0,
      feeRate: 0,
      commissionRate: 0,
      defaultFreight: 0,
    },
  };
}
export function demoState(): State {
  const s = emptyState(),
    date = today();
  const base = {
    category: "Madeira",
    minimum: 10,
    unit: "un" as const,
    notes: "",
    cost: 0,
    stock: 0,
  };
  s.suppliers = [
    {
      id: sid(1),
      name: "Madeiras do Interior",
      phone: "",
      email: "",
      document: "",
      address: "",
      city: "Sorocaba",
      state: "SP",
      zip: "",
      notes: "",
      company: "Madeiras do Interior",
    },
  ];
  s.customers = [
    {
      id: sid(2),
      name: "Mariana Oliveira",
      phone: "",
      email: "",
      document: "",
      address: "",
      city: "Sorocaba",
      state: "SP",
      zip: "",
      notes: "Calopsita: Pipoca",
      company: "",
    },
    {
      id: sid(3),
      name: "Lucas Santos",
      phone: "",
      email: "",
      document: "",
      address: "",
      city: "Itapetininga",
      state: "SP",
      zip: "",
      notes: "",
      company: "",
    },
  ];
  s.materials = [
    {
      ...base,
      id: sid(10),
      name: "Madeira pinus",
      sku: "MAT-001",
      stock: 2400,
      minimum: 600,
      cost: 0.035,
      unit: "cm",
      supplierId: sid(1),
      lastPrice: 0.035,
      lastPurchase: date,
    },
    {
      ...base,
      id: sid(11),
      name: "Corda de algodão",
      sku: "MAT-002",
      category: "Cordas",
      stock: 8,
      minimum: 15,
      cost: 2.5,
      unit: "m",
      supplierId: "",
      lastPrice: 2.5,
      lastPurchase: date,
    },
    {
      ...base,
      id: sid(12),
      name: "Argola inox",
      sku: "MAT-003",
      category: "Ferragens",
      stock: 12,
      minimum: 30,
      cost: 1.85,
      supplierId: "",
      lastPrice: 1.85,
      lastPurchase: date,
    },
    {
      ...base,
      id: sid(13),
      name: "Miçangas naturais",
      sku: "MAT-004",
      category: "Acabamento",
      stock: 240,
      minimum: 100,
      cost: 0.08,
      supplierId: "",
      lastPrice: 0.08,
      lastPurchase: date,
    },
    {
      ...base,
      id: sid(14),
      name: "Embalagem kraft",
      sku: "MAT-005",
      category: "Embalagens",
      stock: 42,
      minimum: 20,
      cost: 2,
      supplierId: "",
      lastPrice: 2,
      lastPurchase: date,
    },
  ];
  s.parts = [
    {
      ...base,
      id: sid(20),
      name: "Madeira 5 cm",
      sku: "PEC-005",
      materialId: sid(10),
      length: 5,
      width: 2,
      height: 2,
      diameter: 0,
      stock: 80,
      cost: 0.2,
    },
    {
      ...base,
      id: sid(21),
      name: "Madeira 10 cm",
      sku: "PEC-010",
      materialId: sid(10),
      length: 10,
      width: 2,
      height: 2,
      diameter: 0,
      stock: 24,
      cost: 0.4,
    },
    {
      ...base,
      id: sid(22),
      name: "Madeira 15 cm",
      sku: "PEC-015",
      materialId: sid(10),
      length: 15,
      width: 2,
      height: 2,
      diameter: 0,
      stock: 18,
      cost: 0.6,
    },
  ];
  const p: Omit<
    Product,
    "id" | "name" | "sku" | "price" | "stock" | "cost" | "recipe" | "image"
  > = {
    ...base,
    category: "Enriquecimento",
    description:
      "Feito à mão com madeira natural e corda de algodão. Diversão e estímulo para a rotina da sua ave. Supervisione o uso e substitua quando apresentar desgaste.",
    species: "Calopsitas",
    size: "M",
    active: true,
    online: true,
    labor: 5,
    overhead: 1,
    extra: 0,
  };
  s.products = [
    {
      ...p,
      id: sid(30),
      name: "Balanço Tropical",
      sku: "BRI-001",
      price: 49.9,
      stock: 8,
      cost: 16.41,
      image: "/images/balanco.svg",
      recipe: [
        { kind: "part", itemId: sid(22), quantity: 2 },
        { kind: "part", itemId: sid(20), quantity: 4 },
        { kind: "material", itemId: sid(11), quantity: 1.5 },
        { kind: "material", itemId: sid(13), quantity: 12 },
        { kind: "material", itemId: sid(12), quantity: 2 },
        { kind: "material", itemId: sid(14), quantity: 1 },
      ],
    },
    {
      ...p,
      id: sid(31),
      name: "Escada Natural",
      sku: "BRI-002",
      price: 39.9,
      stock: 10,
      cost: 12.9,
      image: "/images/escada.svg",
      recipe: [
        { kind: "part", itemId: sid(21), quantity: 5 },
        { kind: "material", itemId: sid(11), quantity: 1 },
        { kind: "material", itemId: sid(12), quantity: 2 },
        { kind: "material", itemId: sid(14), quantity: 1 },
      ],
    },
    {
      ...p,
      id: sid(32),
      name: "Móbile Alegria",
      sku: "BRI-003",
      price: 34.9,
      stock: 3,
      cost: 11.1,
      image: "/images/mobile.svg",
      recipe: [
        { kind: "part", itemId: sid(20), quantity: 6 },
        { kind: "material", itemId: sid(11), quantity: 0.8 },
        { kind: "material", itemId: sid(13), quantity: 10 },
        { kind: "material", itemId: sid(12), quantity: 1 },
        { kind: "material", itemId: sid(14), quantity: 1 },
      ],
    },
  ];
  s.orders = [
    {
      id: sid(40),
      number: 1024,
      customerId: sid(2),
      items: [
        {
          productId: sid(30),
          quantity: 20,
          unitPrice: 49.9,
          name: "Balanço Tropical",
        },
        {
          productId: sid(31),
          quantity: 10,
          unitPrice: 39.9,
          name: "Escada Natural",
        },
      ],
      date,
      deadline: date,
      discount: 0,
      freight: 0,
      total: 1397,
      payment: "Pix",
      status: "Aguardando produção",
      notes: "Separar para retirada.",
      source: "painel",
      sold: false,
    },
    {
      id: sid(41),
      number: 1025,
      customerId: sid(3),
      items: [
        {
          productId: sid(32),
          quantity: 5,
          unitPrice: 34.9,
          name: "Móbile Alegria",
        },
      ],
      date,
      deadline: date,
      discount: 0,
      freight: 0,
      total: 174.5,
      payment: "Pix",
      status: "Novo",
      notes: "",
      source: "loja",
      sold: false,
    },
  ];
  s.productions = [
    {
      id: sid(50),
      productId: sid(30),
      quantity: 12,
      date,
      deadline: date,
      responsible: "Proprietária",
      priority: "Alta",
      status: "Planejada",
      cost: 0,
      orderId: sid(40),
      notes: "",
    },
  ];
  // Histórico demonstrativo explícito, com valores fictícios.
  for (let month = 0; month < 6; month++) {
    const d = new Date(date + "T12:00:00");
    d.setMonth(d.getMonth() - month);
    d.setDate(1);
    const dt = d.toISOString().slice(0, 10);
    s.sales.push({
      id: sid(100 + month),
      orderId: sid(200 + month),
      productId: sid(30),
      name: "Balanço Tropical",
      quantity: 25 + month * 2,
      revenue: (25 + month * 2) * 49.9,
      cost: (25 + month * 2) * 16.41,
      profit: (25 + month * 2) * (49.9 - 16.41),
      date: dt,
      customerId: sid(2),
      payment: "Pix",
    });
    s.expenses.push({
      id: sid(300 + month),
      name: "Despesas do ateliê (exemplo)",
      category: "Custos fixos",
      amount: 260,
      date: dt,
      notes: "Dado fictício de demonstração",
    });
  }
  return s;
}
